version: '3.6'
services:
  blackfire:
    container_name: ddev-${DDEV_SITENAME}-blackfire
    image: blackfire/blackfire
    ports: ['8707']
    environment:
      BLACKFIRE_SERVER_ID: '007d05bf-dcc2-4f39-b471-5f10b9124b69'
      BLACKFIRE_SERVER_TOKEN: '410e2b6f98e1ab239370e15663162ebc447ff4774ad5db5b3a589ded5fb1c8ef'
    hostname: ${DDEV_SITENAME}-blackfire
  web:
    links:
      - blackfire:blackfire